/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

/* 

   _id: uuid(),
    title: "Dot Punk",
    artist: "Peter Notrott",
    desc: "Oil on canvas| Dimensions: 60x60cm",
    img: "https://cdn.singulart.com/artworks/v2/cropped/6305/main/fhd/1053013_b1fc42ad416a6c5eaeea01a726e0d41b.jpeg",
    price: 888,
    original_price: 1000,
    rating: 3,
    rated_by: 10,
    categoryName: "Digital Art",
    inStock: true,
    fastDelivery: true,*/

export const products = [
  {
    _id: "ROGUNHRYMMD3M2A",
    title: "REAL MADRID JERSEY",
    description: "",
    price: 599,
    // discountPercentage: 12.9,
    rating: 4,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20220701/849978f27d335c2cc6cbb695323b691c.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: true,
  },
  {
    _id: "74CFP45BIEZAN1E",
    title: "TOTTENHAM HOTSPUR JERSEY",
    description: "",
    price: 499,
    // discountPercentage: 12.9,
    rating: 3,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20230414/08875f4dea59f3bfa48575cc03a96776.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: false,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "AK7KADVMLGTR7M3",
    title: "BARCELONA JERSEY",
    description: "",
    price: 399,
    // discountPercentage: 12.9,
    rating: 3.5,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20230415/1e3c4f5eb00c1624017fe084d9ac45eb.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: false,
  },

  {
    _id: "2ROGUNHRYMMD3M2",
    title: "MANCHESTER CITY JERSEY",
    description: "",
    price: 599,
    // discountPercentage: 12.9,
    rating: 3.9,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20230522/1228f3d9ff9f351fb7c92801b25e08c8.png=z-0,0_f-webp",
    inStock: false,
    fastDelivery: false,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "KJMC7CXF5GJLFWH",
    title: "CHELSEA JERSEY",
    description: "",
    price: 299,
    // discountPercentage: 12.9,
    rating: 2.5,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20220728/5dc7c0fc2ed64ec21683070691f0c21b.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "DST0G3NYLP281NJ",
    title: "JUVENTUS JERSEY",
    description: "",
    price: 299,
    // discountPercentage: 12.9,
    rating: 1.5,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20230513/ce7eb9610f50416650681256138a783b.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: false,
  },

  {
    _id: "YBJB95IGVKRWT1D",
    title: "A.C. MILAN JERSEY",
    description: "",
    price: 349,
    // discountPercentage: 12.9,
    rating: 2.5,
    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20230129/b24eaa6ccba0d71e896c8eb612825198.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: false,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "JC6FMBA12KQZIWI",
    title: "INTER MILAN JERSEY",
    description: "",
    price: 249,
    // discountPercentage: 12.9,
    rating: 3,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20230504/74430a8eaf11f2a232c1d4ce92ef9a6b.png=z-0,0_f-webp",
    inStock: false,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "5AL43F8A4L5QPC5",
    title: "FC BAYERN MUNICH JERSEY",
    description: "",
    price: 349,
    // discountPercentage: 12.9,
    rating: 4,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20220530/d7244f2e1dda44388b3e997819b8fa51.png=z-0,0_f-webp",
    inStock: true,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "51MN9ERXPB887B0",
    title: "BORUSSIA DORTMUND JERSEY",
    description: "",
    price: 299,
    // discountPercentage: 12.9,
    rating: 4.2,

    images:
      "https://cf.projerseyshop.cc/upload/ttmall/img/20220819/a3d58aedef1db03e5c52e9e50bb77d0c.png=z-0,0_f-webp",
    inStock: false,
    fastDelivery: true,
    categoryName: "Jersey",
    isFeatured: false,
  },
  {
    _id: "73G4K9GKHQ1CHIO",
    title: "REAL MADRID SHORTS",
    description: "",
    price: 399,
    // discountPercentage: 12.9,
    rating: 3,
    images:
      "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2ae5ecec3df4a6aa4c0ad2b01292981_9366/real-madrid-21-22-home-shorts.jpg",
    inStock: true,
    fastDelivery: false,
    categoryName: "Shorts",
    isFeatured: true,
  },
  {
    _id: "BZ8QQ9FO7L6NZH0",
    title: "BORUSSIA DORTMUND SHORTS",
    description: "",
    price: 249,
    // discountPercentage: 12.9,
    rating: 3,
    images:
      "https://images.footballfanatics.com/borussia-dortmund/borussia-dortmund-away-shorts-2022-23_ss4_p-13311874+u-16u2caw98y6wpt36gtqi+v-b77f44d6227643bdbf1590c67d3432c0.jpg?_hv=2&w=340",
    inStock: true,
    fastDelivery: true,
    categoryName: "Shorts",
    isFeatured: false,
  },

  {
    _id: "S3682JUPE13H14D",
    title: "JUVENTUS SHORTS",
    description: "",
    price: 199,
    // discountPercentage: 12.9,
    rating: 3,
    images: "https://m.media-amazon.com/images/I/610Yt8ZQgGL._AC_UX679_.jpg",
    inStock: true,
    fastDelivery: true,
    categoryName: "Shorts",
    isFeatured: false,
  },
  {
    _id: "YCGLE06759PUZKT",
    title: "BARCELONA SHORTS",
    description: "",
    price: 149,
    // discountPercentage: 12.9,
    rating: 3,
    images:
      "https://m.media-amazon.com/images/I/61zLjFGwnwL._AC_UL600_FMwebp_QL65_.jpg",
    inStock: false,
    fastDelivery: true,
    categoryName: "Shorts",
    isFeatured: false,
  },
  {
    _id: "IXE96EQ0F6DTQAB",
    title: "MANCHESTER CITY SHORTS",
    description: "",
    price: 99,
    // discountPercentage: 12.9,
    rating: 2,
    images: "https://m.media-amazon.com/images/I/61u+gGNU1NL._AC_UX679_.jpg",
    fastDelivery: true,
    categoryName: "Shorts",
    isFeatured: false,
  },
  {
    _id: "FYDCWJVLO6OWS42",
    title: "JUVENTUS FOOTBALL",
    description: "",
    price: 299,
    // discountPercentage: 12.9,
    rating: 3,
    images: "https://m.media-amazon.com/images/I/81J40YB9IcL._AC_SX679_.jpg",
    inStock: true,
    fastDelivery: false,
    categoryName: "Football",
    isFeatured: false,
  },

  {
    _id: "R8ID2QR6PS29OXO",
    title: "REAL MADRID FOOTBALL",
    description: "",
    price: 399,
    // discountPercentage: 12.9,
    rating: 4,
    images:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTNkuou2E-lCCMbU_QcEc4YRevNclG9qxfkHqgfmRXMPKR43mo_QMNFTGG5eSofpe9QBELDDBW4Tke1UmrvGgYv8c82IFbImPofn8sg3as",
    inStock: true,
    fastDelivery: true,
    categoryName: "Football",
    isFeatured: false,
  },
  {
    _id: "3PVVUXNIN8HHSUW",
    title: "MANCHESTER CITY FOOTBALL",
    description: "",
    price: 299,
    // discountPercentage: 12.9,
    rating: 3,
    images:
      "https://shop.mancity.com/dw/image/v2/BDWJ_PRD/on/demandware.static/-/Sites-master-catalog-MAN/default/dwb379b367/images/large/701225927001_pp_01_mcfc.png?sw=1600&sh=1600&sm=fit",
    inStock: false,
    fastDelivery: false,
    categoryName: "Football",
    isFeatured: false,
  },
  {
    _id: "4CFP45BIEZAN1EA",
    title: "FC BAYERN MUNICH FOOTBALL",
    description: "",
    price: 99,
    // discountPercentage: 12.9,
    rating: 2,
    images:
      "https://m.media-amazon.com/images/I/21mQKDlPnML._AC_UL450_FMwebp_QL65_.jpg",
    inStock: true,
    fastDelivery: true,
    categoryName: "Football",
    isFeatured: true,
  },
  {
    _id: "K7KADVMLGTR7M37",
    title: "BARCELONA FOOTBALL",
    description: "",
    price: 199,
    // discountPercentage: 12.9,
    rating: 3,
    images:
      "https://m.media-amazon.com/images/I/7102z3u7XML._AC_UL600_FMwebp_QL65_.jpg",
    inStock: true,
    fastDelivery: false,
    categoryName: "Football",
    isFeatured: false,
  },
];
